### ISSUE TITLE
Error with pdf creation after all files downloaded

### ISSUE THREAD

**Issue by Theroumag** [vaibhavk97/GoBooDo#19]
Error with pdf creation after all files downloaded with command ``python GoBooDo.py --id={insert id}``
Example with two pdfs, similar errors, just different line numbers
I am using Python 3.8.2 on Linux
```
Traceback (most recent call last):
  File "GoBooDo.py", line 156, in start
    lastFirstList = self.pageList[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GoBooDo.py", line 222, in <module>
    book.start()
  File "GoBooDo.py", line 159, in start
    return self.processBook()
  File "GoBooDo.py", line 147, in processBook
    service.makePdf()
  File "/home/GoBooDo/makePDF.py", line 20, in makePdf
    pdf.image(pagePath,0,0)
  File "/usr/lib/python3.8/site-packages/fpdf/fpdf.py", line 150, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/fpdf/fpdf.py", line 971, in image
    info=self._parsepng(name)
  File "/usr/lib/python3.8/site-packages/fpdf/fpdf.py", line 1844, in _parsepng
    f.read(n+4)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```
```
Traceback (most recent call last):
  File "GoBooDo.py", line 156, in start
    lastFirstList = self.pageList[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GoBooDo.py", line 222, in <module>
    book.start()
  File "GoBooDo.py", line 159, in start
    return self.processBook()
  File "GoBooDo.py", line 147, in processBook
    service.makePdf()
  File "/home/GoBooDo/makePDF.py", line 20, in makePdf
    pdf.image(pagePath,0,0)
  File "/usr/lib/python3.8/site-packages/fpdf/fpdf.py", line 150, in wrapper
    return fn(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/fpdf/fpdf.py", line 971, in image
    info=self._parsepng(name)
  File "/usr/lib/python3.8/site-packages/fpdf/fpdf.py", line 1844, in _parsepng
    f.read(n+4)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by Yolakalemowa** [comment]
Facing same issue.... was it ever resolved?
