### ISSUE TITLE
Facing issue

### ISSUE THREAD

**Issue by resonantperson** [vaibhavk97/GoBooDo#30]
Traceback (most recent call last):
  File "GoBooDo.py", line 26, in <module>
    settings = json.load(ofile)
  File "C:\Users\Praveen Kumar R\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Praveen Kumar R\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Praveen Kumar R\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Praveen Kumar R\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 4 column 26 (char 79)

**Comment by Ilirski** [comment]
I also have the same json.decoder.JSONDecodeError: Invalid \escape: line 4 column 26 (char 79) issue

**Comment by minamotorin** [comment]
Replace `"C:\pass\\to\\tesseract.exe"` in the 4th line of your `setting.json` with `"C:\\pass\\to\\tesseract.exe"`.
`\` muse be escaped.
