### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dmalessio** [vaibhavk97/GoBooDo#32]
Tesseract works perfectly with other applications.

> (1, 'Error opening data file \\Program Files (x86)\\Tesseract-OCR\\tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')
> ------------------- Creating PDF -------------------
> Traceback (most recent call last):
>   File "GoBooDo.py", line 217, in <module>
>     book.start()
>   File "GoBooDo.py", line 197, in start
>     self.processBook()
>   File "GoBooDo.py", line 150, in processBook
>     service.makePdf()
>   File "C:\GoBooDo\makePDF.py", line 15, in makePdf
>     firstPath = self.imageNameList[0]
> IndexError: list index out of range

**Comment by zachlai** [comment]
The same IndexError, wondering how to fix it.

**Comment by nonvieri** [comment]
same here :/

**Comment by sfolje0** [comment]
It works for me on linux (WSL) and I was getting the same error untill I edited/configured the settings in `settings.json` file correctly.

More specifically, as is said in Readme file, you should configure the line:
` "tesseract_path": "C:\\program Files\\Tesseract-OCR\\tesseract.exe", // The path for tesseract engine if not available via environment variables.`

For me on linux it was to change 
`"C:\\program Files\\Tesseract-OCR\\tesseract.exe"` to `"/usr/bin/tesseract"` since I installed tesseract software in that location.

For you please try to change tesseract path from:
`"C:\\program Files\\Tesseract-OCR\\tesseract.exe"`
to:
`"C:\\Program Files (x86)\\Tesseract-OCR\\tesseract.exe"`

Hope, it helps
