### ISSUE TITLE
Periodic crash

### ISSUE THREAD

**Issue by L0que** [vaibhavk97/GoBooDo#4]
Hi, I have this working well, but quite often after searching for the first 30-40 pages or so, I get a crash that looks something like this each time:

Traceback (most recent call last):
  File "GoBooDo.py", line 198, in <module>
    book.start()
  File "GoBooDo.py", line 181, in start
    self.processBook()
  File "GoBooDo.py", line 134, in processBook
    service = createBook(self.name, self.path)
  File "c:\Python\GoBooDo\makePDF.py", line 10, in __init__
    nameList = sorted(os.listdir(os.path.join(path,'Images')),key= lambda x : in
t(x[:-4]))
  File "c:\Python\GoBooDo\makePDF.py", line 10, in <lambda>
    nameList = sorted(os.listdir(os.path.join(path,'Images')),key= lambda x : in
t(x[:-4]))
ValueError: invalid literal for int() with base 10: ''

**Comment by L0que** [comment]
Actually, I believe I may have created that glitch, by placing a folder in the Images folder.  Please ignore.
