### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by athulkrishna2015** [vaibhavk97/GoBooDo#52]
Traceback (most recent call last):
  File "C:\path\GoBooDo-master\GoBooDo.py", line 217, in <module>
    book.start()
  File "C:\path\GoBooDo-master\GoBooDo.py", line 197, in start
    self.processBook()
  File "C:\path\GoBooDo-master\GoBooDo.py", line 150, in processBook
    service.makePdf()
  File "C:\path\GoBooDo-master\makePDF.py", line 15, in makePdf
    firstPath = self.imageNameList[0]
IndexError: list index out of range

**Comment by athulkrishna2015** [comment]
How do I delete This ?
I think I find the answer 
https://github.com/vaibhavk97/GoBooDo/issues/32

**Comment by riyanimbekar** [comment]
How did you fix it? I’m having the same issue

**Comment by athulkrishna2015** [comment]
I could not find the answer
sorry

**Comment by athulkrishna2015** [comment]
check the mentioned issue for possible fix
